name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Install dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install quilt for patch management
      - name: Install quilt
        run: sudo apt-get update && sudo apt-get install -y quilt

      # Install system dependencies for native modules
      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev libx11-dev libxkbfile-dev

      # Run unit tests
      - name: Run patch validation tests
        run: ./scripts/run-unit-tests.sh